### ISSUE TITLE
Could you explain the dynamic require()

### ISSUE THREAD

**Issue by wilsonpage** [lorenseanstewart/nextjs-mdx-blog-kit#4]
First off, great project! Loads of useful techniques and approaches.

I was particularly intregregued about the extraction of the post metadata. i understand the `preval` bit runs at build-time, but was confused about the following line, that runs at runtime:

https://github.com/lorenseanstewart/nextjs-mdx-blog-kit/blob/f84c793e76273af88ad273c796ad34e31550a606/utils/post-list.js#L15

Would be really grateful if you could explain how this works 🙏 Happy to submit a follow-up PR with a comment to explain to any other curious readers 😊

**Comment by lorenseanstewart** [comment]
the `default: Component` above is the `export default` that is implicit in MDX files. In this case I'm pulling out the default export which is the component. 

There is also a `meta` object that is being exported that is being used elsewhere.

```
export const meta = {
    title: "This is my first post",
    tags: ["serverless", "node.js", "python"],
    layout: "post",
    publishDate: "2017-10-02",
    modifiedDate: false,
    seoDescription:
        "This post demonstrates syntax-hightlighted code in your post.",
    exclude: false
};
```
