### ISSUE TITLE
Support for next 9

### ISSUE THREAD

**Issue by redblue9771** [lorenseanstewart/nextjs-mdx-blog-kit#9]
I tried to upgrade to next9, but obviously they are not compatible.

```
Error: 'router' and 'Component' can not be returned in getInitialProps from _app.js https://err.sh/zeit/next.js/cant-override-next-props
```

**Comment by kunalgorithm** [comment]
I'm getting this error even with next 8

**Comment by bleonard** [comment]
Fixed this and a few other things here if you are interested to try it out: https://github.com/lorenseanstewart/nextjs-mdx-blog-kit/pull/10

**Comment by lorenseanstewart** [comment]
Thanks so much @bleonard . 

@redblue9771 this repo is upgraded to use Next 9.

**Comment by redblue9771** [comment]
> Thanks so much @bleonard .
> 
> @redblue9771 this repo is upgraded to use Next 9.

Thank you!
